### ISSUE TITLE
Add input validation for Edit User Profile fields

### ISSUE THREAD

**Issue by Nerdylicious** [systers/macc#10]
Add input validation for the following fields:
- [ ] First Name
- [ ] Last Name
- [ ] Mobile
- [ ] Email
- [ ] Gender
- [ ] Location

Input validation includes not allowing certain special characters, having a maximum length for each field and following a specific format/regex for applicable fields (for example, the phone number field).

**Comment by Neetuj** [comment]
added this as a task
