### ISSUE TITLE
A new design for the interface

### ISSUE THREAD

**Issue by mish24** [systers/macc#101]
![screenshot from 2017-02-12 05-10-04](https://cloud.githubusercontent.com/assets/24610197/22853480/524cc1b2-f07d-11e6-8b8d-aecb3da9bc66.png)

How is this design for the homepage? Can I send a PR to make it look like this? @medhach :)

**Comment by muddlebee** [comment]
#70 Im actually working on this.

**Comment by mish24** [comment]
@anweshknayak This is just for the homepage body, not the entire UI.

**Comment by mish24** [comment]
Included in #70
