### ISSUE TITLE
Add Pcuser details through forms

### ISSUE THREAD

**Issue by mish24** [systers/macc#106]
This will let us add some compulsory features for various Pcuser fields and regex validations. @medhach  
Can I go ahead with it?

**Comment by medhach** [comment]
Could you elaborate on the need?

**Comment by mish24** [comment]
Currently, the data is mostly entered through the template. This makes validation adding regexes difficult, like adding a check whether the number is entered through current format or not. Also, my adding forms we can make first_name a compulsory field easily. Avoids hassle. @medhach :)

**Comment by yatna** [comment]
@mish24 I have opened a similar issue already #97 . I am almost done with my PR.

**Comment by mish24** [comment]
@yatna you created new forms with all validations?

**Comment by yatna** [comment]
@medhach I have tried to pretty much involve everything. If something remains missing you can include that in your PR .

**Comment by mish24** [comment]
@yatna alright! :)
