### ISSUE TITLE
Fix change password functionality

### ISSUE THREAD

**Issue by Nerdylicious** [systers/macc#11]
Fix the change password functionality so that it checks that the **New Password** field and **Confirm Password** field match. Currently, the form is not checking whether the input to these 2 fields match.

**Comment by Neetuj** [comment]
i think this can be a good code in task

**Comment by Neetuj** [comment]
added this as a task

**Comment by Neetuj** [comment]
https://github.com/peacecorps/app-web-server/search?utf8=%E2%9C%93&q=Confirm+password

**Comment by Neetuj** [comment]
using abov link (basically a search you can find where to make this change ) ..its basically in 2 files .. when you setup the password or change the password

**Comment by ishanqut** [comment]
Hi, 

I am more inclined to have a text change listner on each text boxes and disable the button until both are equal to each other. 

Or do you want to validate once the button is clicked? Which would be better? 

Regards 

P.S. I am working on this task through google code in

**Comment by Neetuj** [comment]
@ishanqut where is the Pull request ?

**Comment by ahmedsabie** [comment]
@Neetuj I see that the task is still open on the code in website. My pull request is at #32.

**Comment by Neetuj** [comment]
I approved the task .. can you double check ?

**Comment by ahmedsabie** [comment]
@Neetuj I didn't claim the task yet because my current task is still being reviewed. Can I claim it after?

**Comment by Neetuj** [comment]
Hi

sorry I am not sure which task you are talking about
if its this one ..
Task instance for Ishan Joshi PCHB-Fix change password functionality
(Systers, an Anita Borg Institute Community)

then this was already claimed by Ishan

sorry for the confusion .. but if you are working on another task then this
is the sequence of events

1) claim

2) consult

3) make the change

4) PR

5) approve

**Comment by ahmedsabie** [comment]
oh yeah I am referring to this task, but I still see it on the Google Code in website. I didn't claim it because I am doing another task which is being reviewed, so I thought I would make the pull request first. What should I do?

**Comment by Neetuj** [comment]
This is already done by ishan and approved

**Comment by ahmedsabie** [comment]
ah ok I didn't know that. Thanks for letting me know.
