### ISSUE TITLE
Improving UI for "edit profile"

### ISSUE THREAD

**Issue by mish24** [systers/macc#113]
![screenshot from 2017-02-23 11-49-14](https://cloud.githubusercontent.com/assets/24610197/23225940/cf70370c-f959-11e6-8903-edd7029c5d3c.png)

Not in sync with the current UI for other pages. I actually already modified it. Somehow its not appearing. @medhach Can I change this again?

**Comment by muddlebee** [comment]
Already working in #70 for every view.

**Comment by mish24** [comment]
@anweshknayak I already added the css files and stylesheets before for the profile page. This would just extend that. You can make more changes in your PR independent of all this.

**Comment by mish24** [comment]
included in #70
