### ISSUE TITLE
Add asterisk glyphicons to mandatory inputs

### ISSUE THREAD

**Issue by yatna** [systers/macc#118]
It is a standard practice to display a red colored asterisk glyphicon in front of fields which are mandatory and must be necessarily given by the  user such as password and username while login. I would like to add these across all forms in the project. @medhach I would like to send a PR.

**Comment by muddlebee** [comment]
already in #70

**Comment by yatna** [comment]
@anweshknayak Perhaps we can divide the task, you see #70 is a very broad issue and it is unclear about what specific details that issue will change in the UI. If possible try to add specific details about what all changes you are adding so that other contributors know what more they can add/change and can continue to contribute to the UI as well. Thank You .

**Comment by mish24** [comment]
@medhach Done. Please close.
