### ISSUE TITLE
Add dropdown for Gender in Edit Profile form

### ISSUE THREAD

**Issue by Nerdylicious** [systers/macc#12]
Right now, gender is entered in a text field. Gender should be selected from a dropdown (or radio buttons) instead.

**Comment by Neetuj** [comment]
this one =code in task?

**Comment by Neetuj** [comment]
added this as a task

**Comment by balasankarc** [comment]
Gender being a textbox is actually better than giving options. Take a look at http://www.sarahmei.com/blog/2010/11/26/disalienation/

**Comment by goelakash** [comment]
There is a js script that can be used to make editable drop-downs : 
http://www.dhtmlgoodies.com/scripts/form_widget_editable_select/form_widget_editable_select.html
https://www.zoonman.com/projects/combobox/

**Comment by ishanqut** [comment]
Isn't this already done? It's still up as a code in task. I'm a student doing Google Code In and came across this!

**Comment by prafful002** [comment]
If this issue is still open, can I work on it ?
