### ISSUE TITLE
Removing hard-coded  links for image.

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#122]
https://github.com/systers/macc/blob/develop/ui/header.html#L10
May not be a good idea coming like this. As it is hosted in another site and is not reliable. Takes time to upload too. 

So creating a separate folder for the same and using (https://compressor.io/) to compress the images.

@medhach is this any good ?

**Comment by medhach** [comment]
Sure go ahead!

**Comment by sara-02** [comment]
@medhach @anweshknayak the html page mentioned in the issue, returns a `404` :/

**Comment by medhach** [comment]
@sara-02 Do you still want to work on this? Else, we can close it for now.

**Comment by sara-02** [comment]
@medhach No, I was not working on it, just stating that the description was not upto date

**Comment by medhach** [comment]
Closing issue for now.
