### ISSUE TITLE
[Bug] Link not working on notice.html 

### ISSUE THREAD

**Issue by yatna** [systers/macc#129]
The link back to the signup page are not working on notice.html. This page is displayed when user, enters mismatching passwords, duplicate username etc.
![screenshot from 2017-02-24 03 54 50](https://cloud.githubusercontent.com/assets/8321130/23282016/7a11c2de-fa45-11e6-9484-cd8a8aed0d80.png)
@medhach I would fix this.

**Comment by medhach** [comment]
Go ahead

**Comment by yatna** [comment]
PR Merged #143 
(GSoC Aspirant)
