### ISSUE TITLE
Create Pcuser automatically

### ISSUE THREAD

**Issue by Nerdylicious** [systers/macc#13]
When the application is installed for the first time, the user creates a superuser and is required to create a Pcuser in the Django admin interface (that corresponds to the superuser). This should be done automatically.

**Comment by prafful002** [comment]
@Nerdylicious can you please review my PR and let me know if anything has to be changed ? Thank You.

**Comment by muddlebee** [comment]
@Nerdylicious  could you elaborate this issue ?
