### ISSUE TITLE
[Bug] Edit Profile displays gender incorrectly

### ISSUE THREAD

**Issue by yatna** [systers/macc#130]
The gender field in edit profile shows radio button corresponding to female as checked irrespective of what the real value is. @medhach I would like to fix this,

**Comment by medhach** [comment]
@yatna Maybe you could correct all bugs in 1 PR and send it through?

**Comment by yatna** [comment]
@medhach Sure, but then we may have multiple commits in one PR if we follow the 'one-commit-per-task' rule. Is that fine?

**Comment by medhach** [comment]
@yatna Create an issue with 4-5 such changes, then submit 1 PR with 1 commit explaining all the changes. PR messages can be upto 250 characters so I think its enough for description as well.
