### ISSUE TITLE
[Bug] Pcuser model has incorrect field types

### ISSUE THREAD

**Issue by yatna** [systers/macc#131]
1. Gender is stored as CharField of length 10 . It should be done like this-
`GENDER_CHOICES = [(0, 'Male'), (1, 'Female')]
gender = models.IntegerField(choices=GENDER_CHOICES)`
2. Phone No is stored as CharField of length 150. It should be numeric.

**Comment by mish24** [comment]
done in #112

**Comment by yatna** [comment]
:+1: Closing
