### ISSUE TITLE
Labels not present in edit password and forgot password page.

### ISSUE THREAD

**Issue by yatna** [systers/macc#133]
Absence of labels on the edit profile page makes it very difficult and confusing for user to edit the data. Hence, I propose to add labels horizontally to the corresponding fields. @medhach Can I go ahead?

**Comment by mish24** [comment]
I had something like this included in #113

**Comment by yatna** [comment]
@mish24 Sure, go ahead with that. I will do it for forgot_password and reset_password pages and leave this one to you. :-D

**Comment by yatna** [comment]
Fixed. Closing.
