### ISSUE TITLE
Move first and last names to Pcuser models

### ISSUE THREAD

**Issue by mish24** [systers/macc#135]
Currently we can enter the name only through the site and not even through the admin, hence there's no to make the fields mandatory. If this is moved to models, we can ensure that the user enters the name the first time he/she creates a Pcuser account. Issue can be combined with #134 and resolved. @medhach Is this good?

**Comment by yatna** [comment]
@mish24 first_name and last_name fields are already present in the pcuser model. They are inside the user model which is a part of pcuser model, hence you cannot see it, just like email and password.

**Comment by mish24** [comment]
@yatna Ohh I did not know that, sorry. But then how does one user add first and last names through admin page? Are these also supposed to be added through python shell? In that case it can be left empty too.

**Comment by yatna** [comment]
User is a default model pre-defined under django.contrib.auth class . It has some mandatory fields such as username and password and many other optional fields such as email and first_name etc. Even if you make these optional fields mandatory in the html they will remain optional in the user model. You can read more about the User model and all its fields here https://docs.djangoproject.com/en/1.10/ref/contrib/auth/
You can view all your users with first_name , last_name etc in admin by clicking on the edit option beside the 'Users' under 'Auth' section. Currently the permissions are set to only to add n delete users, but not edit them. It desired these permissions can be changed.

**Comment by yatna** [comment]
I think the first_name and last_name must remain optional as it is only required for displaying and serves no other purpose. So, it must be left to the liberty of the user whether he/she wants to give away his/her name.

**Comment by mish24** [comment]
That makes sense. There was one problem with what the header showed. That's fixed in #137, so I suppose this is not that necessary.
