### ISSUE TITLE
Edit profile button not visible now 

### ISSUE THREAD

**Issue by mish24** [systers/macc#138]
![screenshot from 2017-02-25 10-56-43](https://cloud.githubusercontent.com/assets/24610197/23313712/d12886b2-fae4-11e6-86ee-37e332998a28.png)

The edit profile button isn't there anymore. It was there before.

**Comment by yatna** [comment]
@mish24  It is showing in mine. Are you sure you have pulled the recent changes?

**Comment by mish24** [comment]
@yatna Yes I was running my develop branch only, and it is up to date with upstream.

**Comment by mish24** [comment]
And even after creating a super user and associating a Pcuser with it, it's not logging me in

**Comment by mish24** [comment]
@yatna I checked on a different laptop to be sure, and it turned out that Bootstrap was not working properly in my laptop. So i guess it's not a problem in the code. I'll close this issue
