### ISSUE TITLE
Rename infohub Django app to macc

### ISSUE THREAD

**Issue by Nerdylicious** [systers/macc#15]
Rename infohub (the app that contains project settings) to macc, since MACC is the name of the project.

**Comment by rosariorobinson** [comment]
Can we close this issue now?

**Comment by Neetuj** [comment]
But there is not pull request .. where is the change?

**Comment by Nerdylicious** [comment]
@rosariorobinson @Neetuj 

I haven't changed this yet. This isn't a high priority task, I can try to get to this later though.

**Comment by Neetuj** [comment]
Agree

**Comment by muddlebee** [comment]
@medhach can I claim this ? as no one has took it till now.

**Comment by mikael19** [comment]
Hi,
Can I work on this?

Thanks

**Comment by mayburgos** [comment]
I think this has already been successfully completed. Closing now.
