### ISSUE TITLE
Tests to be added 

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#150]
- [ ] pcsa_GHN

- [ ] pcsa_safety_tools

- [ ] profiles

There are currently no tests present. @medhach I would like to add tests for the same. 
For serializers as well.

**Comment by medhach** [comment]
Yep, submit a PR soon.

**Comment by mish24** [comment]
pcsa_GHN and contacts are the same.

**Comment by muddlebee** [comment]
No just some functionalities of contacts are there in pcsa_GHN. Not the whole.

**Comment by mish24** [comment]
oh my bad. sorry

**Comment by muddlebee** [comment]
@mish24 You can take up the pcsa_GHN part if you want to.

**Comment by mish24** [comment]
@anweshknayak Thanks :)

**Comment by medhach** [comment]
@anweshknayak You working on this right? If yes, you might want to consider the utility functions @mish24  has used in her PR.

**Comment by anweshknayak** [comment]
@medhach sure I will take a look
