### ISSUE TITLE
Uploading profile picture in edit profile

### ISSUE THREAD

**Issue by mish24** [systers/macc#155]
We cannot do that currently. Is this really needed or should we just remove the box from the profile page? Even if it's made optional, a default image must be shown if the user hasn't uploaded any picture.
@medhach What do you think?

**Comment by medhach** [comment]
What do you mean by - we cannot do that currently? Could you specify?

**Comment by mish24** [comment]
There's no way to add profile pictures. There is no field in the model to do so. There has to be a FileField column present for the same. @medhach

**Comment by medhach** [comment]
Lets remove the box for now.

**Comment by mish24** [comment]
Alright ! Shall I work on this then? @medhach

**Comment by mish24** [comment]
@medhach fixed in #176

**Comment by mish24** [comment]
Done in #194. closing.
