### ISSUE TITLE
'Cancel' button on edit profile also adds the changes.

### ISSUE THREAD

**Issue by mish24** [systers/macc#156]
A Pcuser wants to edit the profile, he/she accidentally changes any field, but realises that the change wasn't needed, so they click on the 'Cancel' button. The change shouldn't be there. However, here the 'Cancel' button still changes the field value on its own and shows a success message after that. 
There's error in template rendering as well as with the views. 
@medhach Can I fix this?

**Comment by mish24** [comment]
Basically 'Update' and 'Cancel' buttons are same things

**Comment by yatna** [comment]
@mish24 #149 Deals with the same issue

**Comment by mish24** [comment]
@yatna I'll close this one. You can add in your issue that Update and Cancel do the same things. :)
