### ISSUE TITLE
Hostname issue

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#157]
http://127.0.0.1:8000/

![screenshot from 2017-02-26 01 11 49](https://cloud.githubusercontent.com/assets/8139783/23334236/d11e2d7a-fbc0-11e6-96ef-414ef33f04f9.png)

http://localhost:8000/
![screenshot from 2017-02-26 01 11 31](https://cloud.githubusercontent.com/assets/8139783/23334237/d235af08-fbc0-11e6-8a90-f50535b03bda.png)

Opens up different pages. Where as both are same. Bug ?

**Comment by mish24** [comment]
The first one shows up when you log in as user who has 'staff status' but not superuser status.
For them the site shows something like this. The 'is_staff' and 'is_superuser' are False by default for users created.
You need to give the user superuser status through the initial superuser created manually and then also create a Pcuser first. 
![screenshot from 2017-02-26 13-29-33](https://cloud.githubusercontent.com/assets/24610197/23334404/ad884eb0-fbc3-11e6-9afb-c1049936ce78.png)

This is what I understood as of now.

**Comment by muddlebee** [comment]
@mish24 Umm that shouldn't happen as localhost and127.0.0.1 should point to same page. So this needs to be fixed. Related to #23 . Let me check again.

And Yes I created superuser.  manage.py script automatically makes one.

**Comment by muddlebee** [comment]
Issue is already there for it. Closing this. Related to #23
