### ISSUE TITLE
Adding throttling functionality

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#159]
https://djangopackages.org/packages/p/django-ratelimit/

Advantages: Prevent an attacker from flooding that view and filling up the database with fake users. We want to throttle access to the view and limit the damage an attacker can cause.

Label : Enhancement, New Feature

Same for DRF can be added too (http://www.django-rest-framework.org/api-guide/throttling/)

**Comment by medhach** [comment]
This also could be saved for your GSoC proposal. :)
