### ISSUE TITLE
Add 'Reset' Button to 'Edit Profile' Page

### ISSUE THREAD

**Issue by yatna** [systers/macc#167]
Conventionally, profile editing pages have a reset button which resets all the values in input fields to what they were last saved. This button comes in handy when user has entered some incorrect value and he/she needs to restore the value to what it was earlier.

**Comment by aradhyamathur** [comment]
hello can i take this one ?

**Comment by yatna** [comment]
@aradhyamathur  Sorry, I am working on this. You may take up the issue tagged as 'free'.

**Comment by kakshay21** [comment]
It's been a while... Is this fixed yet? Or can I start?

**Comment by mish24** [comment]
@kakshay21 He's been assigned by a collaborator to fix the issue. Wait for their reply or approval for fixing.

**Comment by medhach** [comment]
@yatna Did you pull a request regarding this? If yes, can you reference it here?

**Comment by mish24** [comment]
I'm taking this one for now. It's been a while.

**Comment by kakshay21** [comment]
fine, I'm not working on this @mish24 
And yeah, It's been really long time @yatna

**Comment by GunpreetAhuja** [comment]
@medhach I have solved this issue. Should I send PR?

**Comment by medhach** [comment]
@GunpreetAhuja Okay but you might want to ask the creator about the issue before you solve it to avoid double work. @yatna Have you solved this issue too? Else, we can go ahead with @GunpreetAhuja .

**Comment by yatna** [comment]
@medhach PR sent #298 . Sorry for delaying the PR.
