### ISSUE TITLE
Unable to add post through safety tools

### ISSUE THREAD

**Issue by mish24** [systers/macc#169]
![screenshot from 2017-02-28 23-38-31](https://cloud.githubusercontent.com/assets/24610197/23393692/98e0d91c-fdaa-11e6-8755-083ccaa30809.png)

This is the error message it shows. However, I couldn't even create a new category through shell. Can I work on this? @medhach

**Comment by medhach** [comment]
um @mish24 this is related to the categories in the PCSA mobile and web apps, so maybe you can postpone this to a GSoC task. I'll try to add a description regarding the proper functionality and how MACC should be working with PCSA soon.
Cheers!

**Comment by mish24** [comment]
Oh understood. :) So shall I close this issue for now? @medhach

**Comment by medhach** [comment]
Sure
