### ISSUE TITLE
Add a little info about the post description in the view

### ISSUE THREAD

**Issue by mish24** [systers/macc#170]
![screenshot from 2017-02-28 23-45-00](https://cloud.githubusercontent.com/assets/24610197/23393837/9369e496-fdab-11e6-85c3-65e4c7de4c53.png)

Here both of the posts have the same title. There is a lot of place remaining in the right. I was thinking that we could add a small amount of description (like 10-15 words then '...') as a sort of preview to the description. @medhach Should I do this? Or would it be better to make post titles unique as well?

**Comment by medhach** [comment]
yeah go head and submit  a PR!

**Comment by mish24** [comment]
Done in #193
