### ISSUE TITLE
User can have unauthorized access to other user's url and profile info

### ISSUE THREAD

**Issue by mish24** [systers/macc#173]
![screenshot from 2017-03-01 00-25-03](https://cloud.githubusercontent.com/assets/24610197/23394837/41d1079e-fdb1-11e6-926d-2d2ff0316242.png)
![screenshot from 2017-03-01 06-36-24](https://cloud.githubusercontent.com/assets/24610197/23406450/06e528c0-fde5-11e6-98d7-f36e581b384c.png)

In the screenshot, the header says welcome, user. This means no first name has been set up. But if the user tries to type another id number in the url, he/she is able to access another user's profile info, just as shown in the screenshot. And this is for all the pages. @medhach Can I work on this?

**Comment by medhach** [comment]
Okay :)

**Comment by mish24** [comment]
Solved in #201
