### ISSUE TITLE
Date created field 

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#180]
In post field across every apps.

**Comment by mish24** [comment]
@anweshknayak I tried to add one more field in Pcuser actually, it showed some programming error. I googled it and it mentioned that in 1.6 we cannot really update the fields like that.
for reference - http://stackoverflow.com/questions/1605662/django-syncdb-and-an-updated-model

**Comment by muddlebee** [comment]
There is an django-app called south. @mish24 should work.

**Comment by mish24** [comment]
@anweshknayak Yeah I did read about that, I guess it should. It's deprecated now so there are not many references for it

**Comment by muddlebee** [comment]
@medhach probably add this to version 2 milestone. When django gets ported to 1.8+ This feature will be helpful.
