### ISSUE TITLE
User can enter white space to save data.

### ISSUE THREAD

**Issue by mish24** [systers/macc#185]
![screenshot from 2017-03-02 06-07-26](https://cloud.githubusercontent.com/assets/24610197/23460250/6bbaa4c6-feaa-11e6-91fb-71aea477eafd.png)
![screenshot from 2017-03-02 06-07-32](https://cloud.githubusercontent.com/assets/24610197/23460248/6a07148e-feaa-11e6-90d9-d0d2c73e0951.png)

User can enter a white space and save empty data here.

**Comment by yatna** [comment]
@mish24 It is not getting saved in mine. 
![screenshot from 2017-03-01 22 21 50](https://cloud.githubusercontent.com/assets/8321130/23470892/9c742dd0-fecd-11e6-9300-6d5fddd2ab7b.png)

**Comment by mish24** [comment]
@yatna Umm, that's weird. But I updated my branch. I'll recheck this and then open the issue.

**Comment by yatna** [comment]
:+1:

**Comment by mish24** [comment]
The issue is that user can enter a white space here to save blank items. Reopening the issue

**Comment by medhach** [comment]
@mish24 How are you planning to solve this issue?

**Comment by mish24** [comment]
@medhach I was thinking of overwriting the save method and using strip() function.

**Comment by medhach** [comment]
Go ahead and submit a PR

**Comment by mish24** [comment]
Solved in #205
