### ISSUE TITLE
Forgot Password doesn't work

### ISSUE THREAD

**Issue by mish24** [systers/macc#186]
![screenshot from 2017-03-02 12-00-27](https://cloud.githubusercontent.com/assets/24610197/23474943/a4641c7c-fedb-11e6-927f-07affd0ef2fd.png)

After entering username and email, this message is shown. @medhach Shall I fix this?

**Comment by mish24** [comment]
![screenshot from 2017-03-02 11-58-35](https://cloud.githubusercontent.com/assets/24610197/23475265/05252712-fedd-11e6-819c-8a1e7b24abde.png)
This too :P

**Comment by medhach** [comment]
@mish24 Sure go ahead, also take care of the header and footer for this page along with the other design issues ;)

**Comment by mish24** [comment]
On it!

**Comment by mish24** [comment]
Done in #204

**Comment by amittbhardwj** [comment]
is this issue fixed yet or not?

**Comment by mish24** [comment]
The issue is fixed, I will make the necessary changes as suggested by @medhach ! Maybe you could take up an issue which is free (there are quite a few)
