### ISSUE TITLE
[Enhancement] Change default gender in 'SignUp' form

### ISSUE THREAD

**Issue by yatna** [systers/macc#187]
Currently the default gender in the 'Signup' form is set to 'Male'. However, since we have added a third 'Restricted' gender option, I think the default value (pre-set value) must be set to 'Restricted' so that if the user does not choose any value in the form, the value must be set to restricted .

**Comment by medhach** [comment]
@yatna Maybe we don't need to have any default? What do you think?

**Comment by aradhyamathur** [comment]
hello can i take this up ?

**Comment by yatna** [comment]
@medhach Yeah, I guess that won't be bad either. However, since gender is an mandatory field in the form, we will have to put a check to make sure that one of the 3 radio buttons is checked. Should I change the PR

**Comment by medhach** [comment]
@yatna Did you change your PR?

**Comment by mish24** [comment]
@medhach Issue can be closed. Done in #188, Need to solve conflicts.
