### ISSUE TITLE
Incorrect links on page that appears when user tries to sign up with an existing username or email

### ISSUE THREAD

**Issue by Raxerz** [systers/macc#197]
![page 1](https://cloud.githubusercontent.com/assets/16686007/23556392/819a8dd4-0052-11e7-9fcf-d8ca4cf99cd6.png)

There are 2 separate links here:
one for "Click" and the other for "here", both of them redirect to two different pages.

"Click" redirects to the following page (Forgot password page):
![page 3](https://cloud.githubusercontent.com/assets/16686007/23556537/f427c3b2-0052-11e7-932c-9db67ddc971e.png)

"here" redirects to the following page (Sign up page):
![page 2](https://cloud.githubusercontent.com/assets/16686007/23556557/02a07614-0053-11e7-888e-8bc87c290c14.png)

**Comment by medhach** [comment]
@Raxerz There is already a student working on this. :)

**Comment by Raxerz** [comment]
Oh sorry @medhach. Will close the issue now. :)
