### ISSUE TITLE
Layout needs to be fixed

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#208]
![screenshot from 2017-03-10 22 59 02](https://cloud.githubusercontent.com/assets/8139783/23805806/67de3da8-05e5-11e7-80a2-cdf9237dead9.png)

**Comment by mish24** [comment]
Solved in #204

**Comment by muddlebee** [comment]
No

**Comment by mish24** [comment]
![screenshot from 2017-03-11 23-27-31](https://cloud.githubusercontent.com/assets/24610197/23821057/e43165b6-064d-11e7-9d49-96d90dea4659.png)

#204 solved it somehow. I wasn't able to do the radio buttons

**Comment by aradhyamathur** [comment]
What changes are to be made in the layout ??

**Comment by muddlebee** [comment]
@aradhyamathur you see the Attribute names and Box layout(for input) are not properly alligned. Same is to be done to radio buttons.

**Comment by aradhyamathur** [comment]
ohk will work on it

**Comment by aradhyamathur** [comment]
i have made some corrections to the layout as follows ; shall I put a PR for the same
![screenshot from 2017-03-12 02 42 11](https://cloud.githubusercontent.com/assets/6674956/23826925/abfeb934-06cd-11e7-840a-77a4ec65da4f.png)

**Comment by muddlebee** [comment]
Still not alligned. This shouldn't be hard. Just place the Attributes(Male) and checkbox under one class div="row" and in child div(checkbox and respective attributes) do the needfull. It should be easy with bootstrap. @aradhyamathur

**Comment by aradhyamathur** [comment]
ohk will check it currently the code has implemented the form  with table tags. Will modify it accordingly @anweshknayak
