### ISSUE TITLE
Button click issue

### ISSUE THREAD

**Issue by Raxerz** [systers/macc#211]
![screenshot from 2017-03-12 12 32 37](https://cloud.githubusercontent.com/assets/16686007/23829752/1b3a9938-0720-11e7-8a32-3c0b695d4401.png)

For the buttons "Go to Malaria" and "Go to PC", the onclick listener works only on clicking over the text inside the button and not the button as a whole.

**Comment by Raxerz** [comment]
This seems to be an issue for almost all of the buttons on all pages.

**Comment by mish24** [comment]
@Raxerz Hey! I Think this issue has already been opened and someone was working on it. It was related to hyperlinks.

**Comment by Raxerz** [comment]
@mish24  are you referring to this #117 ? 
Has the issue been fixed? I pulled the latest changes and the bugs seem to still exist.

**Comment by mish24** [comment]
It was supposed to be. I guess you should fix all other links, but comment once about this issue on that PR as well. @Raxerz

**Comment by amittbhardwj** [comment]
@mish24 I see it is not yet fixed and my approach would be to make links appear as buttons using bootstrap classes.

**Comment by medhach** [comment]
Closing the issue. #117 was merged.
