### ISSUE TITLE
Remove contact number as input field.

### ISSUE THREAD

**Issue by Raxerz** [systers/macc#212]
Contact number is an input field on the contact list page. This has to be fixed as it misleads the user.
![screenshot from 2017-03-12 12 44 26](https://cloud.githubusercontent.com/assets/16686007/23829837/e4f9e03e-0721-11e7-9c42-4d84c3a5b9c3.png)

**Comment by mish24** [comment]
What else do you propose?

**Comment by Raxerz** [comment]
@mish24 I suggest we make the field readonly, disable it or  leave it as an innerHTML text.

**Comment by medhach** [comment]
@Raxerz Maybe this should be left alone till GSoC period starts. We are looking for a few changes in the app so this feature may or may not be there. :)
