### ISSUE TITLE
Header should go up too as the page is scrolled down

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#219]
![screenshot from 2017-03-18 02 57 35](https://cloud.githubusercontent.com/assets/8139783/24063734/e34bf330-0b86-11e7-9e03-a3abf6fd4b16.png)

**Comment by muddlebee** [comment]
or few changes can be done to this. UI should be proper. Invisible CSS property for header would do.

**Comment by mikael19** [comment]
HI @anweshknayak ,
Please is there an update on this?
Can I work on this as a bug fix for GSoC17 ?

Thanks.

**Comment by muddlebee** [comment]
@kera99 sure

**Comment by mikael19** [comment]
Ok, I'm on it.😊

**Comment by mikael19** [comment]
@anweshknayak To get this done, I had to remove the "navbar-fixed-top" class from the nav in the  base.html file at macc/infohub/templates/infohub/.
Is there any other thing you would like me to do on this task ? Or can I go ahead with a PR ?

**Comment by mikael19** [comment]
I have submitted a pull request for this issue. Here it is: https://github.com/systers/macc/pull/256
