### ISSUE TITLE
Modify the installation guide for a local machine

### ISSUE THREAD

**Issue by alessbn** [systers/macc#222]
- The [requirements](https://github.com/systers/macc/blob/develop/docs/Installation%20Guide.md#requirements) sections is confusing because only mention that it is a tutorial for an Ubuntu Virtual Machine and not for a local machine.

- The step number seven ([Install Project Dependencies](https://github.com/systers/macc/blob/develop/docs/Installation%20Guide.md#install-project-dependencies)) needs to remove `sudo` because is using a virtual environment for a local installation.

**Comment by muddlebee** [comment]
@alessbn ssbn there ain't any necessity to change readme for your 1st point as it is universal for all linux OSes. And no need to remove sudo as you can just create a virtual environment using virtualenv "environment name" and use it accordingly everytime.

**Comment by alessbn** [comment]
@anweshknayak thank you for your observation, I forgot to specify in which case, running `pip install` command using `sudo` for _requirements.txt_, by doing this the dependencies will not be installed on the virtual environment, for installing the dependencies on the virtual environment you only need `pip install` command

**Comment by muddlebee** [comment]
`pip install -r requirements.txt` should do right. 
and sudo it is not the issue here. It's with the permission settings of your own Linux Machine. You can change it accordingly to the $USER in your bash profile or whichever you are using.
