### ISSUE TITLE
No validation for strong passwords

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#224]
The password field accepts even single letter passwords. There is no validation as that of minimum 8 characters. Even spaces are accepted. I would like to add validations to the field.

(a GSoC aspirant)

**Comment by medhach** [comment]
@GunpreetAhuja Go ahead and submit a PR!

**Comment by GunpreetAhuja** [comment]
Pull request: https://github.com/systers/macc/pull/267
