### ISSUE TITLE
Minimum length for PCSA post description

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#225]
There is no minimum length set for the description field in the post for PCSA.

(a GSoC aspirant)

**Comment by mish24** [comment]
Why do we need a minimum length? A description "describes" the post, and it might be related to any disease or the remedy in this case. I don't see the point of having a limit for this.

**Comment by GunpreetAhuja** [comment]
At least a few words could be compulsory to be added in order for the user to understand the title. Currently, entering only a single letter works.

![image](https://cloud.githubusercontent.com/assets/6309072/24147781/3d99f624-0e12-11e7-9d8e-74a999c3835e.png)

**Comment by muddlebee** [comment]
Yes it is a good idea @GunpreetAhuja. It may affect the frontend layout if overflow is caused by text.
Either you could
1. Do changes in backend . (min-length in the model)
2. or add some css property which will contain the text area if it overflows

@medhach

**Comment by mish24** [comment]
@GunpreetAhuja What minimum length do you propose?

**Comment by GunpreetAhuja** [comment]
@mish24 Well, it depends on the requirement of the project. I would suggest to keep it at least 50-100 characters.

**Comment by medhach** [comment]
Go ahead and pull a request! 100 characters should be good as minimum. :)

**Comment by GunpreetAhuja** [comment]
Pull request: https://github.com/systers/macc/pull/253
