### ISSUE TITLE
Office name accepts special characters

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#226]
Office name should be a field that accepts only alphabets or my be numbers (not sure, if numbers need to be allowed). However, the office name value accepts special characters as well.
Besides the phone number field has only length validation and no format validation.

![image](https://cloud.githubusercontent.com/assets/6309072/24118576/a55de402-0d84-11e7-87ab-3b35fb59aefb.png)

**Comment by mish24** [comment]
@GunpreetAhuja There's a similar issue already opened
