### ISSUE TITLE
Webpages are not responsive ( Why we are not using Bootstrap!!)

### ISSUE THREAD

**Issue by amittbhardwj** [systers/macc#229]
I think we should **make webpages look beautiful and responsive** and **I would suggest using Bootstrap and would like to implement it** on web pages. From these screenshots we can see that when we resize the window, the buttons hid and the lower portion of website is also not visible

A GSOC Aspirant

<img width="1280" alt="screen shot 2017-03-20 at 4 35 56 pm" src="https://cloud.githubusercontent.com/assets/5919457/24120697/e6014f9c-0d8b-11e7-82cc-e66f4bc5611b.png">
<img width="927" alt="screen shot 2017-03-20 at 4 36 26 pm" src="https://cloud.githubusercontent.com/assets/5919457/24120699/e60208ec-0d8b-11e7-9041-88a05b68a01b.png">
<img width="724" alt="screen shot 2017-03-20 at 4 36 40 pm" src="https://cloud.githubusercontent.com/assets/5919457/24120700/e602299e-0d8b-11e7-8e46-5c400352cb93.png">
<img width="1382" alt="screen shot 2017-03-20 at 4 37 10 pm" src="https://cloud.githubusercontent.com/assets/5919457/24120698/e6019ace-0d8b-11e7-8474-b826684a2403.png">

**Comment by muddlebee** [comment]
Bootstrap is already there

**Comment by amittbhardwj** [comment]
@anweshknayak it is not working properly then.

**Comment by muddlebee** [comment]
@amittbhardwj bootstrap has not been used just the library is there itself. and this issue is not relevant. Try seeing the other issues.

**Comment by amittbhardwj** [comment]
@anweshknayak are we planning to use it?

**Comment by muddlebee** [comment]
it's already been used in some parts of code. Not whole. you can use it where it hasn't been use already.

**Comment by amittbhardwj** [comment]
yes, I have seen it and i think most of issues will be solved if it is imlemented properly.

**Comment by mish24** [comment]
@amittbhardwj  Maybe the issue here is that you want to integrate Bootstrap to reduce the manual coding involved to make the pages responsive. But this will alter all the CSS and HTML files altogether. Even the layouts are different for some parts of the site. i suggest you work on the pages which lack the Bootstrap features. Maybe look at the pages rendered using jinja2?

**Comment by GunpreetAhuja** [comment]
@amittbhardwj  This issue https://github.com/systers/macc/issues/214 might satisfy your point.

**Comment by muddlebee** [comment]
@amittbhardwj start with including button layout in mobile view for the "Profile" And "Log out". That would do as a first step

**Comment by amittbhardwj** [comment]
@mish24 shouldn't we have uniform layout design and yes we should reduce the manual coding. If something is available to help our work and is stable and used in huge number of projects, why we should be left behind. Altering CSS and HTML files is not that big issue. I will see to the pages and post screenshots.

**Comment by medhach** [comment]
@amittbhardwj Screenshots will solve half the confusion and explain the work in better detail! :)

**Comment by amittbhardwj** [comment]
@medhach sure, I will post screenshots here

**Comment by amittbhardwj** [comment]
@medhach Here are few screenshots of new layouts
(A GSOC aspirant) 
<img width="1280" alt="screen shot 2017-03-30 at 6 58 47 pm" src="https://cloud.githubusercontent.com/assets/5919457/24572846/890141ae-164a-11e7-9282-b299722e647f.png">
<img width="1280" alt="screen shot 2017-03-30 at 7 57 53 pm" src="https://cloud.githubusercontent.com/assets/5919457/24572848/890abaea-164a-11e7-987a-fbece0fb6267.png">
<img width="1280" alt="screen shot 2017-03-30 at 8 25 18 pm" src="https://cloud.githubusercontent.com/assets/5919457/24572847/89096104-164a-11e7-9fff-469992c4238a.png">
<img width="1280" alt="screen shot 2017-03-30 at 8 51 05 pm" src="https://cloud.githubusercontent.com/assets/5919457/24572849/8911588c-164a-11e7-9c51-fb4f7eb8362d.png">

**Comment by medhach** [comment]
Add this to your proposal. 👍

**Comment by amittbhardwj** [comment]
@medhach can I send direct PR to this issue as Systers Community disqualified me for GSOC under section 2.4 . I still want to contribute to this project regardless of the GSOC.
