### ISSUE TITLE
Port to latest version of Django

### ISSUE THREAD

**Issue by amittbhardwj** [systers/macc#230]
While looking at the code and relating issues, i noticed that most the issues here can be solved by porting the application to newest stable version of django and it will also increase the stability and long term support of the application. i would like to put myself forth for this task as I have developed  in Django versions from 1.7 to 1.9.

A GSOC Aspirant

**Comment by mish24** [comment]
@amittbhardwj This can't be handled via pull request(s). A lot of things have to be changed for this purpose. Also, can you elaborate what issues persisting here can be solved by having a higher version?

**Comment by amittbhardwj** [comment]
@mish24 you can refer to this link https://docs.djangoproject.com/en/1.10/releases/ . A lot has changed and most of it good like native password validation, improvement to sql connections and more robust approach to django principle.

**Comment by medhach** [comment]
@amittbhardwj We're going to have this as a GSoC task this year. :)
