### ISSUE TITLE
Render the same page after an invalid entry 

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#231]
On entering erroneous data in Signup page, the url is directed to a different page to display the error messages. This would be more convenient if the error message is shown on the top of the same page. This would save a user's click.

![image](https://cloud.githubusercontent.com/assets/6309072/24157827/e47b0276-0e30-11e7-8338-a92da9f2662d.png)

(a GSoC aspirant)

**Comment by mish24** [comment]
@GunpreetAhuja That's because the views are rendered by Jinja as of now. To change this we need to alter the jinja views completely and add the changes to the existing template engine of Django. And this is the flow of the site as of now. Maybe @medhach can guide you more for how to go about it.

**Comment by GunpreetAhuja** [comment]
@mish24 I have worked on this and the screenshot provided does not alter the jinja views as such. Only the rendered page and the data is required to be changed.
Apart from this, the notice.html template would no longer be needed.

**Comment by GunpreetAhuja** [comment]
#236 pull request

**Comment by GunpreetAhuja** [comment]
#237 pull request

**Comment by GunpreetAhuja** [comment]
Pull request https://github.com/systers/macc/pull/239

**Comment by GunpreetAhuja** [comment]
Pull request https://github.com/systers/macc/pull/245

**Comment by GunpreetAhuja** [comment]
Resolving the same issue on login page as well. 
Pull Request: https://github.com/systers/macc/pull/264
