### ISSUE TITLE
Edit profile form has no mandatory fields

### ISSUE THREAD

**Issue by HarinderKaur11** [systers/macc#234]
In the edit profile form, all the fields can be left blank and still the user profile can be updated. Some essential fields are required to be made mandatory. At least, the 'mobile' and 'location' fields should be mandatory for the user to fill, as these are compulsory fields in the sign-up form.
![screenshot 7](https://cloud.githubusercontent.com/assets/25227750/24162162/026c95cc-0e3d-11e7-8e57-544c43e44cac.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/25227750/24162172/08a3732a-0e3d-11e7-9335-3bfd87a44f78.png)

**Comment by mish24** [comment]
@HarinderGithub Why should they be made mandatory? The purpose is not to create a profile, but to have an account of the Pcuser to add/edit or access information. What's the best that can be done here is removal of the fields that don't have any value entered by the user in the 'Profile' section. But making the fields mandatory is not required (it's up to the user completely)

**Comment by HarinderKaur11** [comment]
@mish24 My point is that at least the fields that are mandatory in the sign-up form should be mandatory in the edit profile form as well in order to maintain consistency between sign up and edit profile forms as both these forms serve the same purpose of taking up users' information and storing in the database.
Or the other way around, we can give users the flexibility of signing up by just creating an account with username and password. In this case, we need to redesign the sign-up form.

**Comment by medhach** [comment]
@HarinderGithub Go ahead and  submit a PR! Keep in mind to have a proper commit message! :)

**Comment by HarinderKaur11** [comment]
Sure! Thanks @medhach :)
