### ISSUE TITLE
A small UI change

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#235]
As per wireframes and general view, I made this improvement in the UI to make it more appealing:

Before change:
![image](https://cloud.githubusercontent.com/assets/6309072/24163058/d5947e18-0e3f-11e7-999a-0ed0ad02c35e.png)

After change:
![image](https://cloud.githubusercontent.com/assets/6309072/24166072/7c5e469a-0e48-11e7-88a1-d8e9919874c1.png)

Similarly other templates can as well be modified for better design.

(a GSoC aspirant)

**Comment by medhach** [comment]
Good one! Send a PR!
Could you also change the copyright year to 2017?

**Comment by GunpreetAhuja** [comment]
@medhach Sure :)

**Comment by GunpreetAhuja** [comment]
I have included the UI change in https://github.com/systers/macc/pull/237 pull request itself.
