### ISSUE TITLE
Category Id should be a dropdown input with category name instead of input field

### ISSUE THREAD

**Issue by amittbhardwj** [systers/macc#238]
The category id input field should be a dropdown menu because the user doesn't know the category ids and it will take more then single attempt for a user to save post , which will be hectic for the user. Other solution I suggest is that we can change Category Id to Category and instead of number dropdown we can provide the dropdown of category names which will be more useful to a user.

A GSOC Aspirant

<img width="1280" alt="screen shot 2017-03-23 at 3 54 51 pm" src="https://cloud.githubusercontent.com/assets/5919457/24267912/396d41a6-0fe2-11e7-981a-dc85c1fc30b0.png">

**Comment by mish24** [comment]
@amittbhardwj All of this is on hold right now :(

**Comment by amittbhardwj** [comment]
can we create a new label for issues that will be on hold?

**Comment by mish24** [comment]
I opened #169 but had to close. At least when we get more info we can re open them anytime.

**Comment by medhach** [comment]
Yes @amittbhardwj We are planning to integrate with the PCSA app this time but we still need confirmation from Peace Corps so this will be on hold. :)
