### ISSUE TITLE
[Enhancement] Modify README.md

### ISSUE THREAD

**Issue by alessbn** [systers/macc#240]
@medhach I would like to add headers to paragraphs:

- Mobile App Control Center (MACC)
- On Malaria App
- On FirstAide App

For a look like this:
![readme-2-1](https://cloud.githubusercontent.com/assets/10042008/24318754/0e6938b8-10d0-11e7-8c06-6cca21ea4185.png)

**Comment by medhach** [comment]
Sure go ahead!

**Comment by apoorvaagupta** [comment]
Hello, Is this issue still open. I would like to take it up if no one else is working on it.

**Comment by sara-02** [comment]
@apoorvaagupta the only way to find out, is look through the open PRs, if none exists then go ahead and work on it.

**Comment by GunpreetAhuja** [comment]
@apoorvaagupta There hasn't been any work done regarding this task. You can very well go ahead!

**Comment by mayburgos** [comment]
We're using a new Readme template moving forward.
