### ISSUE TITLE
Change title to details.html and policies.html

### ISSUE THREAD

**Issue by alessbn** [systers/macc#241]
Title tag are the same for both html files:

`<title> About PC </title>`

The content of the title tags needs to be changed by:

- Policies
- Important Details

Could I fix this?

**Comment by sreejakshetty** [comment]
@alessbn have you fixed this?If not I would like to work upon this.

**Comment by alessbn** [comment]
@kamishettysreeja25 I was waiting for approval and in order to modify the files :(
in order to respect the [Contribuiton Guide](https://github.com/systers/macc/blob/develop/docs/Contribution.md#avoid-doing-the-following-mistakes)

**Comment by sreejakshetty** [comment]
@alessbn I have talked to @MeepyMay regarding this. Since the approval process is slow we can fix any issue which has not yet fixed.
Thanks :)
