### ISSUE TITLE
Editing Installation guide for better understanding

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#244]
The installation guide has the following line that tends to confuse the installer of whether to keep the lines commented or to remove the comment(hash) tag:

"Comment out the following lines like so:
#import dj_database_url
#DATABASES['default'] =  dj_database_url.config()"

It should be edited to:

"The following lines need to be commented or kept as such if already commented:
#import dj_database_url
#DATABASES['default'] =  dj_database_url.config()"

(a GSoC aspirant)

**Comment by medhach** [comment]
send a PR

**Comment by GunpreetAhuja** [comment]
PR: https://github.com/systers/macc/pull/259
