### ISSUE TITLE
Feature Request: Integration with different languages- Localization

### ISSUE THREAD

**Issue by sreejakshetty** [systers/macc#246]
**Feature Description**: Implement localization in different languages as it will make this system reach many people across the world.
Implementing  a dropdown where we will show the list of languages available. After selecting one of the languages user can view the site in respective language.

Sample wireframes for dropdown:
![local2](https://cloud.githubusercontent.com/assets/14835922/24347693/c4f830c0-12f6-11e7-8eaa-789e0ea07102.png)
![local1](https://cloud.githubusercontent.com/assets/14835922/24347694/c4fb42d8-12f6-11e7-94a1-22f4c85ea204.png)

After implementing localization we will be reaching out to many people across the world who could not understand English language.
@medhach I would like to work on this issue.
Thank you

**Comment by medhach** [comment]
This is a great idea! I would recommend you to add this to your proposal as a GSoC task and work it out then. :)

**Comment by sreejakshetty** [comment]
I have added this feature to my proposal and I have submitted my proposal for review please kindly review it and provide feedback.
