### ISSUE TITLE
Add placeholder field to textboxes

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#270]
I would like to add placeholders as an example is predefined text "Your name" in the textbox "username", placeholder text of "Your Title here.." in the textbox "Title" and so on.

*1
![screen shot 2017-04-17 at 2 04 14 pm](https://cloud.githubusercontent.com/assets/6309072/25098492/c665a3c6-2376-11e7-98e3-370f87e55c78.png)

(a GSoC aspirant)

**Comment by GunpreetAhuja** [comment]
A better way to do this would be to remove the labels and keep the placeholders:

*2
![screen shot 2017-04-17 at 10 13 48 pm](https://cloud.githubusercontent.com/assets/6309072/25111815/3e6db22a-23bb-11e7-988d-1e93dae3b8e9.png)

What do you suggest: @medhach ?

**Comment by yatna** [comment]
1. Keeping both Placeholder and Labels is not a good idea as they both convey exactly the same information most of the times, hence increasing information redundancy.
2. I think the current system of using labels is better over placeholder as - 
 -> Labels display additional information about which fields are mandatory and which are not, by displaying a red asterisk.
-> Placeholders can not be used for fields involving radio buttons, check boxes etc. Hence, labels will be mandatory for them.  Therefore, using placeholder for half the form and labels for half the form isnt s a good idea, and sticking to the current scheme will ensure consistency throughout the form.

**Comment by GunpreetAhuja** [comment]
@yatna I agree with you, but it is that placeholders and labels both already been used in a few parts of the project. Moreover, the placeholders give a more dynamic look to the app which is always appealing.
As far as the concern regarding mandatory fields, it can be fulfilled without using labels as well:
- either in the placeholder field itself or
- outside the input box.
Also, radio buttons could better be replaced by dropdown lists which wouldn't require a label as the default value selected in the dropdown indicated the label itself.
