### ISSUE TITLE
Webhub and Profile views.py

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#271]
What different tasks do the 2 files do? From what I have examined is that the profiles/views.py is redundant and all the tasks are done by webhub/views.py or may be vise versa.
Is there anything specific that the profiles/views.py has been created or should we remove that file code to reduce redundancy?

**Comment by HarinderKaur11** [comment]
@GunpreetAhuja The profile views are called via urls.py and yes webhub views are redundant
