### ISSUE TITLE
Redundant folder pcsa 

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#277]
I am not sure if the the pcsa folder has any definite purpose. The pcsa_GHN and pcsa_safety_tools have all their files defined in them. I think that pcsa should either be removed or used for functionalities common to both pcsa_GHN and pcsa_safety_tools. Keeping both would only increase redundancy.

**Comment by mish24** [comment]
They are different. Safety tools and Get help now have different purpose. The details of Safety Tools have to be provided by PCSA that's why it is on hold right now!

**Comment by yatna** [comment]
Right now the pcsa folder does not seem to be serving any specific purpose as we cannot add any pcsa posts as specified in the folder , but I guess it will in the future as more details are given by the peace corps regarding their requirement. Hence we should keep it for now.
