### ISSUE TITLE
Provision to change email id and verify that email address[Enhancement]

### ISSUE THREAD

**Issue by HarinderKaur11** [systers/macc#289]
While going through the profile module, I noticed that change email address functionality is missing and also if a user changes the email address it should be handled by separate view followed by verification of that email.

**Comment by mish24** [comment]
#175 was approved by @medhach

**Comment by HarinderKaur11** [comment]
I checked #175 but, I making a point that it should be there :)

**Comment by mish24** [comment]
@HarinderGithub E-mail isn't something which must be allowed to change through frontend. Plus, we cannot really change the email id created through admin interface of Django.

**Comment by HarinderKaur11** [comment]
@mish24 all the apps have this functionality to change email address and also, we can change email address through django admin. Its just that we there no code in the views to change the email address. I have done it in other apps also. I strongly believe that it should be there.
