### ISSUE TITLE
Webhub urls.py referencing to the views of other apps

### ISSUE THREAD

**Issue by HarinderKaur11** [systers/macc#290]
Webhub urls.py file is referencing the view functions of other apps which should be referenced by the respective apps urls.py. It makes the code difficult to find and debug for the developer and backward referencing is also tiresome in this case.

**Comment by mish24** [comment]
Duplicacy like #286 and #273. These can be combined to one issue.

**Comment by HarinderKaur11** [comment]
Yes, these can be but then it will be a big PR to merge, so its good to do in parts I guess, rest @medhach can tell
