### ISSUE TITLE
Add favicon to entire project.

### ISSUE THREAD

**Issue by mikael19** [systers/macc#292]
This is an improvement. 
This requires that a favicon is displayed in the browser tab, rather than an "empty" file icon.
If approved, I @kera99 shall take care of this.
@MeepyMay @medhach Can I?

**Comment by medhach** [comment]
@kera99 I think its a great idea. Are you still ready to work on this?

**Comment by GunpreetAhuja** [comment]
@medhach This is done.

**Comment by Saichethan** [comment]
Check this out

https://goo.gl/images/e3syfn

**Comment by GunpreetAhuja** [comment]
Favicon is always the logo of the organization. So we should preferably use the PeaceCorps logo.

**Comment by Saichethan** [comment]
Ok I'm sorry and thank you for mentioning this

**Comment by sara-02** [comment]
@medhach as per @GunpreetAhuja comment this issue is already done, do we still need to keep this issue open?

**Comment by medhach** [comment]
Closing issue. It has been resolved.
