### ISSUE TITLE
Uniform header

### ISSUE THREAD

**Issue by mikael19** [systers/macc#293]
This is an improvement. 
This requires that all pages in the project have a uniform header design (though they can differ in specifics). 
If approved,  I @kera99 shall take care of this.

**Comment by GunpreetAhuja** [comment]
The pages in the project do have a common header style. Can you be more specific about it?

**Comment by yatna** [comment]
@GunpreetAhuja I think kera99 is referring to the non-uniformity in the size and color of the headers as they are not same across all pages.

**Comment by muddlebee** [comment]
@kera99 it need not be done now. First the UI should be uniform and consistent. Which is not yet done now. After that part is done. You can move ahead this with issue. Doing this will be futile as UI will be revamped so your work will be a waste. Rather wait for it.

**Comment by mikael19** [comment]
@anweshknayak . Ok, I will rather do it later. Thanks for that insight. ;)

**Comment by medhach** [comment]
@yatna @GunpreetAhuja Whats the status of this issue?

**Comment by GunpreetAhuja** [comment]
@kera99  Was supposed to work on it. If she hasn't done anything yet, I can take the issue.

**Comment by medhach** [comment]
@GunpreetAhuja Im assigning it to you.

**Comment by GunpreetAhuja** [comment]
@medhach I just missed committing some new added files. Please merge the new pull request as well.
