### ISSUE TITLE
Proper alignment of template files

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/macc#299]
The template files are a bit illegible and their structure needs to be aligned properly.

**Comment by medhach** [comment]
Go ahead and pull a request.

**Comment by GunpreetAhuja** [comment]
@medhach I have done this issue but there a some files that were modified in templates or added new and I missed them committing. I need those files merged first so that I can format them as well without having any conflicts. The files have been committed in pull request: https://github.com/systers/macc/pull/302
