### ISSUE TITLE
Week1 : Mockups

### ISSUE THREAD

**Issue by yatna** [systers/macc#303]
Login
![capture](https://cloud.githubusercontent.com/assets/8321130/26813809/8e87b936-4a9e-11e7-9cba-24b3be43f15d.PNG)

Signup
![capture1](https://cloud.githubusercontent.com/assets/8321130/26813919/478d2a56-4a9f-11e7-951f-ccd167c522e0.PNG)

Forgot Password
![capture2](https://cloud.githubusercontent.com/assets/8321130/26813820/9c7068f4-4a9e-11e7-87ac-4125c709f81f.PNG)

Dashboard
![capture3](https://cloud.githubusercontent.com/assets/8321130/26813821/9c74728c-4a9e-11e7-9018-97a1a69ccf31.PNG)

View Profile
![capture4](https://cloud.githubusercontent.com/assets/8321130/26813822/9c84cb78-4a9e-11e7-800d-c173c6f57ec3.PNG)

Edit Password
![capture5](https://cloud.githubusercontent.com/assets/8321130/26813823/9c9f493a-4a9e-11e7-92ed-91975156b42b.PNG)

For the rest of the pages, there are no major UI changes in them, we will just be extending this color scheme and give them the same header and footer as in these mockups, to give uniformity to the website.

**Comment by medhach** [comment]
A few changes you can consider ->
1.  Add Names for forms Login and Signup.
2. Instead of M/F in gender(signup form), name the third choice 'Other'
Everything else is good, go ahead and pull a request with the scripts.
We'd like to see the application to be more mobile-friendly compared to last year. :)

**Comment by yatna** [comment]
Sure, we will keep these suggestions in mind. ☺️

**Comment by amittbhardwj** [comment]
@yatna @medhach For login page, we can also add a checkbox for "Remember Me" to save credential for next time login. Also, we can lighten the color of header and footer ( just a suggestion). I have posted some screenshots in issue #229 , if you want to refer. :)

**Comment by GunpreetAhuja** [comment]
Yes @amittbhardwj , we will be implementing the "Remember Me" checkbox. Thanks for the suggestion. :)
