### ISSUE TITLE
Write tasks for Google Code-In 2016

### ISSUE THREAD

**Issue by Nerdylicious** [systers/macc#31]
Write tasks for Google Code-In 2015 (https://developers.google.com/open-source/gci/?hl=en) which Systers will be participating in. Assigning this to myself since I'm planning on being a mentor.

**Comment by Neetuj** [comment]
+1

**Comment by Neetuj** [comment]
added some initial setup tasks and picked up 3 bugs from the issue list as tasks ..not sure how many students we are getting but lets talk more on what all tasks we can add

**Comment by Neetuj** [comment]
this is done .. i guess we can close this

**Comment by medhach** [comment]
@Neetuj @Nerdylicious Is there work still pending on this issue?

**Comment by Nerdylicious** [comment]
@medhach We need to come up with more tasks for Google Code-in next year. So if you find a bug/improvement that you don't have time to do during the summer, just add it as an issue.
