### ISSUE TITLE
Porting Unit Tests from Automated-Testing into MACC 

### ISSUE THREAD

**Issue by Tahirih-Natang** [systers/macc#348]
Tests should come along with the project or they are barely useless. Especially, unit tests are tightly coupled with code. Moving all the unit tests code in the automated-test repo into where the code base for MACC lives will be a good thing.
Let me know what you think @MeepyMay @medhach @Janiceilene

**Comment by medhach** [comment]
@Tahirih-Natang I think its a good idea. Can you locate me to the tests that you want to add in the project?

**Comment by Tahirih-Natang** [comment]
@medhach  here is some of the already written  [unit-tests ](https://github.com/systers/automated-testing/tree/develop/MACCTests2017/tests/unit) for this repo.

**Comment by medhach** [comment]
Closing issue, since the PR #354 has been merged.
