### ISSUE TITLE
Remove trailing "p" tag

### ISSUE THREAD

**Issue by valerycodes** [systers/macc#349]
## Description
Remove trailing "p" tag on post display in view post. 

## Mocks

![trailing_p_tag](https://user-images.githubusercontent.com/11312834/36072576-f7f894d8-0f21-11e8-9f69-506f3b737155.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by medhach** [comment]
@valerycodes Go ahead an submit a PR :)
