### ISSUE TITLE
Search Box Alignement in both Firefox and Chrome

### ISSUE THREAD

**Issue by valerycodes** [systers/macc#350]
## Description
The Search boxes are not properly aligned when viewed on Firefox and Chrome browsers. Apart from making them to align properly, added to some style to it will also looks good

## Mocks

#Firefox Display
![firefox_search_box](https://user-images.githubusercontent.com/11312834/36072683-083984a4-0f24-11e8-94ac-bb74a4e98bbe.png)

#Chrome Display
![chrome_search_box](https://user-images.githubusercontent.com/11312834/36072684-086e8212-0f24-11e8-8bc4-aee4e3ca58fb.png)

## Acceptance Criteria
- [x] All three widgets should display on the same horizontal alignment

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by medhach** [comment]
@valerycodes You can go ahead with this. Make sure you make it compatible with all screen sizes. Once you're done, post screenshots so we can review them.
