### ISSUE TITLE
Storing phone number in model to follow internationally standardized format E.164

### ISSUE THREAD

**Issue by valerycodes** [systers/macc#352]
## Description
This is likely to be the most universal way to store phone numbers, given that the app users may have international numbers to work with. In the current model, `BigIntegerField()` has been used to store phone numbers. Adding proper validation to it or replacing it with proper phone number field should get the job done

## Mocks
![contact](https://user-images.githubusercontent.com/11312834/36072887-cac5225a-0f27-11e8-9b87-8ca71230f80a.png)

### Update [Required]
- [ ]Field shoud reject all inputs that doesn't follow format E.164 format

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor

**Comment by medhach** [comment]
@valerycodes How do you plan on achieving this?

**Comment by valerycodes** [comment]
This can be achieved by using a char field, validate it by employing some combination of formatting and then attempting to contact the number immediately to verify.

**Comment by Tahirih-Natang** [comment]
@valerycodes @medhach It can also be done by installing the django-phonenumber-field libray and then import it in the model
I can take on this one 💯
