### ISSUE TITLE
Add PCSA logo picture in Dashboard

### ISSUE THREAD

**Issue by medhach** [systers/macc#59]
Try to get a relevant picture to add in the Dashboard for PCSA app

**Comment by mish24** [comment]
@medhach Can I get going with this?

**Comment by medhach** [comment]
@mish24 Sure, go ahead!

**Comment by mish24** [comment]
Hello! I was trying to find some pics to add to the homepage for macc, and
I came across these. Are these images fine? The picture we have currently
for malaria doesn't give any indication about it, but in this one there are
people with mosquito nets. I thought I'd ask once about the images before
sending a PR.

**Comment by medhach** [comment]
@mish24 Did you attach your photos?

**Comment by mish24** [comment]
I did. I've sent them to you in the mail. I thought it would be better to
ask privately before adding the changes.

**Comment by mish24** [comment]
![macc_malaria](https://cloud.githubusercontent.com/assets/24610197/22698126/b2d8a048-ed79-11e6-8752-04a09ba3bb48.jpg)
![macc_pcsa](https://cloud.githubusercontent.com/assets/24610197/22698125/b2b63684-ed79-11e6-8de2-05bb5c672075.png)

I sent them to you via email. Here are the pics

**Comment by mish24** [comment]
@medhach logo appears now, issue can be closed
