### ISSUE TITLE
Improve UI ?

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#70]
Bootstrap or further improvement in UI ?

- [ ] Adding material fonts

- [ ] separate css folder.

- [ ] bootstrapping views

**Comment by medhach** [comment]
@anweshknayak Can you give more details about what improvements you suggest?

**Comment by muddlebee** [comment]
@medhach Bootstrap is not being used much. I am thinking of making frontend more responsive and beautify it ? what do you say ?

**Comment by medhach** [comment]
Make the changes and post your screenshots here, we can discuss them better that way. :)

**Comment by muddlebee** [comment]
@medhach On it

**Comment by mish24** [comment]
#76 Will this help you? @anweshknayak

**Comment by medhach** [comment]
@anweshknayak #82 is included in this isn't it? I yes, please close that issue. :)

**Comment by muddlebee** [comment]
@medhach no it is a separate issue. Or shall I include that in this ? Please let me know

**Comment by medhach** [comment]
Improving UI will include improving responsiveness in various devices too, so yes maybe we should include that issue here too. You can start working on it, step by step and keep posting screenshots.

**Comment by mish24** [comment]
![screenshot from 2017-02-08 10-41-08](https://cloud.githubusercontent.com/assets/24610197/22702578/3a102ef2-ed87-11e6-933d-de6789567807.png
![screenshot from 2017-02-08 10-53-41](https://cloud.githubusercontent.com/assets/24610197/22702973/82637aa0-ed88-11e6-8698-57e7338652cc.png)

Changes for responsiveness

**Comment by muddlebee** [comment]
@medhach that's a good idea. I will keep posting. Thanks

**Comment by muddlebee** [comment]
- [x] Beautify buttons for Profile and log out 

- [ ] Beautify button for Welcome and log out
