### ISSUE TITLE
Separate the html and static files

### ISSUE THREAD

**Issue by mish24** [systers/macc#76]
The templates have the css styling embedded in them. This causes a lot of problems in finding out common glitches as well. Also, #22 and #21 are also related to the same problem. I want to create an entire independent styling structure and resolved from the templates. @medhach Is this worth it?

**Comment by muddlebee** [comment]
@mish24 There is bootstrap library present already. Independent styling structure as in separate CSS classes ?

**Comment by mish24** [comment]
This. Create a new static folder and move all common css there.

**Comment by muddlebee** [comment]
Yeah sounds good.
