### ISSUE TITLE
Change the user interface for profile

### ISSUE THREAD

**Issue by mish24** [systers/macc#85]
![screenshot from 2017-02-09 13-28-08](https://cloud.githubusercontent.com/assets/24610197/22754965/42c09aa6-ee67-11e6-911a-cf5918f273b9.png)

Can I take up the task to make this page better too?

**Comment by Neetuj** [comment]
yes please :)

**Comment by mish24** [comment]
@Neetuj On it!

**Comment by mish24** [comment]
![screenshot from 2017-02-09 23-58-54](https://cloud.githubusercontent.com/assets/24610197/22771834/61dba5e0-eebf-11e6-8f2f-bb1634f63707.png)

I will add responsiveness to this page too. Also, after the profile is edited by a person, clicking on back button sends you back to the changes made only. So I think I'll include a link for the homepage there as well.

**Comment by mish24** [comment]
#88 Please have a look :)
![screenshot from 2017-02-08 10-40-46](https://cloud.githubusercontent.com/assets/24610197/22799956/c0778786-ef2d-11e6-95af-a7ffacd52957.png)
![screenshot from 2017-02-08 10-41-02](https://cloud.githubusercontent.com/assets/24610197/22799945/bc9d60ea-ef2d-11e6-82cd-a3732b89311f.png)
![screenshot from 2017-02-08 10-41-08](https://cloud.githubusercontent.com/assets/24610197/22799954/bfa31a64-ef2d-11e6-8572-001756e0d465.png)
![screenshot from 2017-02-08 10-53-41](https://cloud.githubusercontent.com/assets/24610197/22799953/bf25a3e0-ef2d-11e6-9cbb-e228bda31f13.png)
![screenshot from 2017-02-10 11-29-55](https://cloud.githubusercontent.com/assets/24610197/22799946/bca0e7ec-ef2d-11e6-93a4-55d791341de2.png)
![screenshot from 2017-02-10 11-30-17](https://cloud.githubusercontent.com/assets/24610197/22799951/be734a10-ef2d-11e6-8eb0-2987b00ac6ea.png)
![screenshot from 2017-02-10 11-30-27](https://cloud.githubusercontent.com/assets/24610197/22799947/bcd40d66-ef2d-11e6-98eb-865f2257e098.png)
