### ISSUE TITLE
Reducing load time of web pages by using Bootstrap CDN

### ISSUE THREAD

**Issue by yatna** [systers/macc#93]
Currently, the project uses a local copy of bootstrap on the server side instead of Bootstrap CDN.

Avantage of using the Bootstrap CDN:
Many users already have downloaded Bootstrap from MaxCDN when visiting another site. As a result, it will be loaded from cache when they visit your site, which leads to faster loading time. Also, most CDN's will make sure that once a user requests a file from it, it will be served from the server closest to them, which also leads to faster loading time.

I propose to add CDN by adding few lines in the html pages and also keep the local copy in case of a fallback.
More can be read here - http://stackoverflow.com/questions/26192897/should-i-use-bootstrap-from-cdn-or-make-a-copy-on-my-server
@medhach @neetuj Should I send a PR?

**Comment by medhach** [comment]
Sure, go ahead!

**Comment by yatna** [comment]
Fixed via #108
