### ISSUE TITLE
Add validations to forms

### ISSUE THREAD

**Issue by yatna** [systers/macc#97]
In various forms there are certain problems. eg in edit profile form-
1. 'First name' field can be left empty, it should be made mandatory.
2. 'Mobile Number' allows text too. It should be limited to numbers.
3. 'Email' field allows invalid emails.
@medhach  I would like to add validations to these forms and send a PR.

**Comment by GunpreetAhuja** [comment]
The first name field is automatically filled with username if left blank. So there is no such issue.

**Comment by medhach** [comment]
@yatna Send a PR.
@GunpreetAhuja The username and the First name cannot be the same so I think we need to fix it.

**Comment by yatna** [comment]
Done
