### ISSUE TITLE
Change Welcome and Logout hyperlinks to buttons.

### ISSUE THREAD

**Issue by yatna** [systers/macc#98]
The welcome and logout buttons are not buttons, but rather hyperlinks with borders. I would like to change then to button of appropriate types.
@medhach I would like to work on this.

**Comment by mish24** [comment]
@yatna already fixed in #88

**Comment by yatna** [comment]
@mish24 This PR is different from the fixes in #88 as I propose to add the Bootstrap button class and remove the hyperlinks whereas you in your PR have removed the border and maintained the text as hyperlinks.

**Comment by mish24** [comment]
@medhach Done!
